---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by vdatcu.
--- DateTime: 11/05/2018 14:08
---

local tests = {
    "src.test.adobe.mocka.HealthcheckTest",
    "src.test.adobe.mocka.argparseTest",
    "src.test.adobe.mocka.projectRootTest",
    "src.test.adobe.mocka.spyTestNginx",
    "src.test.adobe.mocka.isNgxNginx"
}

require("mocka.suite")(tests)