---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by vdatcu.
--- DateTime: 11/05/2018 14:08
---

local tests = {
    "src.test.adobe.mocka.HealthcheckTest"

}

require("mocka.suite")(tests)