---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by vdatcu.
--- DateTime: 11/05/2018 14:10
---

test("Mocka is loaded and works", function()
    local dummyValue = {}
    local nilValue
    assertEquals(1, 1)
    assertNotNil(dummyValue)
    assertNil(nilValue)
    assertNotEquals(1, 2)
end)